pipeline{
    agent any
    stages{
        stage('Git Checkout'){
            steps{
                git branch: 'Jenkins', url" https://github.com/sharath050175/inetbankingv4.git
            }
        }    
        stage('Build'){
            steps{
                echo 'Building the project...'
            }

        }
    }

}